title: Manoa Roommate Radar
description: Connecting Roommates from the University of Hawaii
theme: jekyll-theme-slate
url: https://roommate-radar.github.io/
#github:
#  is_project_page: true
# repository_url: https://github.com/UPDATE-ME!
