title: Manoa Roommate Radar
description: Connecting Roommates from the University of Hawaii
theme: jekyll-theme-slate
github:
  is_project_page: true
  repository_url: https://github.com/roommate-radar/roommate-radar.github.io
